[book]
authors = ["Brandon Williams"]
language = "en"
src = "src"
title = "hashi"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
