name: gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RUSTFLAGS: -D warnings

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rustdoc
        run: make doc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: design/package-lock.json

      - name: Install Docusaurus dependencies
        run: cd design && npm ci

      - name: Build Docusaurus site
        run: cd design && npm run build

      - name: stage build artifacts
        run: |
          mkdir site
          mv ./target/doc site/rustdoc
          mv design/build site/design

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
