name: Move CI

on:
  pull_request:

env:
  MOVE_PACKAGES_PATH: packages

jobs:
  check-formatting:
    name: Check Move formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MystenLabs/move-formatter-action@v1
        with:
          prettier-plugin-move-version: "latest"
          working-directory: ${{ env.MOVE_PACKAGES_PATH }}
