[package]
name = "hashi-antithesis"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
e2e-tests = { path = "../e2e-tests" }
hashi = { path = "../hashi" }
hashi-types = { path = "../hashi-types" }

antithesis_sdk = "0.3.0"
anyhow.workspace = true
bitcoin.workspace = true
clap.workspace = true
corepc-client.workspace = true
fastcrypto.workspace = true
futures.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sui-crypto.workspace = true
sui-futures.workspace = true
sui-rpc.workspace = true
sui-sdk-types.workspace = true
tokio.workspace = true
tracing.workspace = true

[[bin]]
name = "hashi-antithesis"
path = "src/main.rs"
